[workspace]
resolver = "2"

members = [
    "gamercade_app",
    "gamercade_audio",
    "gamercade_cli",
    "gamercade_console",
    "gamercade_core",
    "gamercade_editor",
    "gamercade_fs",
    "gamercade_protos",
    "gamercade_rs",
    "gamercade_sound_engine",
    "gamercade_tools",
]
