use std::{fmt::Display, ops::Index, str::FromStr};

use serde::{self, Deserialize, Serialize};
use serde_big_array::BigArray;

use super::{Color, ColorIndex, PALETTE_COLORS};
use crate::BYTES_PER_PIXEL;

#[derive(Clone, Copy, Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct PaletteIndex(pub u8);

impl FromStr for PaletteIndex {
    type Err = &'static str;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if let Ok(num) = s.parse() {
            Ok(Self(num))
        } else {
            Err("couldn't parse PaletteIndex from str")
        }
    }
}

impl Display for PaletteIndex {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Palette {
    #[serde(with = "BigArray")]
    pub colors: [Color; PALETTE_COLORS],
}

impl Index<ColorIndex> for Palette {
    type Output = Color;

    fn index(&self, index: ColorIndex) -> &Self::Output {
        &self.colors[index.0 as usize]
    }
}

impl Palette {
    /// Gets the raw color, ignoring any kind of transparency
    pub fn color(&self, color_index: ColorIndex) -> Color {
        self[color_index]
    }

    /// Gets colors slice, but as rgba color data
    pub fn as_pixel_colors(&self) -> [[u8; BYTES_PER_PIXEL]; PALETTE_COLORS] {
        self.colors.map(|color| color.into_pixel_data())
    }

    pub fn default_palette_collection() -> Vec<(Palette, &'static str)> {
        vec![
            (Self::resurrect64(), "RESURRECT 64"),
            (Self::aap64(), "AAP-64"),
            (Self::journey(), "JOURNEY"),
            (Self::endesga64(), "ENDESGA 64"),
            (Self::famicube(), "FAMICUBE"),
            (Self::blknx64(), "BLK NX64"),
            (Self::tpp20(), "THE PERFECT PALETTE 2.0"),
            (Self::sweetcanyonextended64(), "SWEET CANYON EXTENDED 64"),
            (Self::pastel64(), "PASTEL-64"),
            (Self::rewild64(), "REWILD 64"),
        ]
    }

    pub fn resurrect64() -> Self {
        Self {
            colors: [
                Color::from_hex(0x2e222fff),
                Color::from_hex(0x3e3546ff),
                Color::from_hex(0x625565ff),
                Color::from_hex(0x966c6cff),
                Color::from_hex(0xab947aff),
                Color::from_hex(0x694f62ff),
                Color::from_hex(0x7f708aff),
                Color::from_hex(0x9babb2ff),
                Color::from_hex(0xc7dcd0ff),
                Color::from_hex(0xffffffff),
                Color::from_hex(0x6e2727ff),
                Color::from_hex(0xb33831ff),
                Color::from_hex(0xea4f36ff),
                Color::from_hex(0xf57d4aff),
                Color::from_hex(0xae2334ff),
                Color::from_hex(0xe83b3bff),
                Color::from_hex(0xfb6b1dff),
                Color::from_hex(0xf79617ff),
                Color::from_hex(0xf9c22bff),
                Color::from_hex(0x7a3045ff),
                Color::from_hex(0x9e4539ff),
                Color::from_hex(0xcd683dff),
                Color::from_hex(0xe6904eff),
                Color::from_hex(0xfbb954ff),
                Color::from_hex(0x4c3e24ff),
                Color::from_hex(0x676633ff),
                Color::from_hex(0xa2a947ff),
                Color::from_hex(0xd5e04bff),
                Color::from_hex(0xfbff86ff),
                Color::from_hex(0x165a4cff),
                Color::from_hex(0x239063ff),
                Color::from_hex(0x1ebc73ff),
                Color::from_hex(0x91db69ff),
                Color::from_hex(0xcddf6cff),
                Color::from_hex(0x313638ff),
                Color::from_hex(0x374e4aff),
                Color::from_hex(0x547e64ff),
                Color::from_hex(0x92a984ff),
                Color::from_hex(0xb2ba90ff),
                Color::from_hex(0x0b5e65ff),
                Color::from_hex(0x0b8a8fff),
                Color::from_hex(0x0eaf9bff),
                Color::from_hex(0x30e1b9ff),
                Color::from_hex(0x8ff8e2ff),
                Color::from_hex(0x323353ff),
                Color::from_hex(0x484a77ff),
                Color::from_hex(0x4d65b4ff),
                Color::from_hex(0x4d9be6ff),
                Color::from_hex(0x8fd3ffff),
                Color::from_hex(0x45293fff),
                Color::from_hex(0x6b3e75ff),
                Color::from_hex(0x905ea9ff),
                Color::from_hex(0xa884f3ff),
                Color::from_hex(0xeaadedff),
                Color::from_hex(0x753c54ff),
                Color::from_hex(0xa24b6fff),
                Color::from_hex(0xcf657fff),
                Color::from_hex(0xed8099ff),
                Color::from_hex(0x831c5dff),
                Color::from_hex(0xc32454ff),
                Color::from_hex(0xf04f78ff),
                Color::from_hex(0xf68181ff),
                Color::from_hex(0xfca790ff),
                Color::from_hex(0xfdcbb0ff),
            ],
        }
    }
    pub fn aap64() -> Self {
        Self {
            colors: [
                Color::from_hex(0x060608ff),
                Color::from_hex(0x141013ff),
                Color::from_hex(0x3b1725ff),
                Color::from_hex(0x73172dff),
                Color::from_hex(0xb4202aff),
                Color::from_hex(0xdf3e23ff),
                Color::from_hex(0xfa6a0aff),
                Color::from_hex(0xf9a31bff),
                Color::from_hex(0xffd541ff),
                Color::from_hex(0xfffc40ff),
                Color::from_hex(0xd6f264ff),
                Color::from_hex(0x9cdb43ff),
                Color::from_hex(0x59c135ff),
                Color::from_hex(0x14a02eff),
                Color::from_hex(0x1a7a3eff),
                Color::from_hex(0x24523bff),
                Color::from_hex(0x122020ff),
                Color::from_hex(0x143464ff),
                Color::from_hex(0x285cc4ff),
                Color::from_hex(0x249fdeff),
                Color::from_hex(0x20d6c7ff),
                Color::from_hex(0xa6fcdbff),
                Color::from_hex(0xffffffff),
                Color::from_hex(0xfef3c0ff),
                Color::from_hex(0xfad6b8ff),
                Color::from_hex(0xf5a097ff),
                Color::from_hex(0xe86a73ff),
                Color::from_hex(0xbc4a9bff),
                Color::from_hex(0x793a80ff),
                Color::from_hex(0x403353ff),
                Color::from_hex(0x242234ff),
                Color::from_hex(0x221c1aff),
                Color::from_hex(0x322b28ff),
                Color::from_hex(0x71413bff),
                Color::from_hex(0xbb7547ff),
                Color::from_hex(0xdba463ff),
                Color::from_hex(0xf4d29cff),
                Color::from_hex(0xdae0eaff),
                Color::from_hex(0xb3b9d1ff),
                Color::from_hex(0x8b93afff),
                Color::from_hex(0x6d758dff),
                Color::from_hex(0x4a5462ff),
                Color::from_hex(0x333941ff),
                Color::from_hex(0x422433ff),
                Color::from_hex(0x5b3138ff),
                Color::from_hex(0x8e5252ff),
                Color::from_hex(0xba756aff),
                Color::from_hex(0xe9b5a3ff),
                Color::from_hex(0xe3e6ffff),
                Color::from_hex(0xb9bffbff),
                Color::from_hex(0x849be4ff),
                Color::from_hex(0x588dbeff),
                Color::from_hex(0x477d85ff),
                Color::from_hex(0x23674eff),
                Color::from_hex(0x328464ff),
                Color::from_hex(0x5daf8dff),
                Color::from_hex(0x92dcbaff),
                Color::from_hex(0xcdf7e2ff),
                Color::from_hex(0xe4d2aaff),
                Color::from_hex(0xc7b08bff),
                Color::from_hex(0xa08662ff),
                Color::from_hex(0x796755ff),
                Color::from_hex(0x5a4e44ff),
                Color::from_hex(0x423934ff),
            ],
        }
    }
    pub fn journey() -> Self {
        Self {
            colors: [
                Color::from_hex(0x050914ff),
                Color::from_hex(0x110524ff),
                Color::from_hex(0x3b063aff),
                Color::from_hex(0x691749ff),
                Color::from_hex(0x9c3247ff),
                Color::from_hex(0xd46453ff),
                Color::from_hex(0xf5a15dff),
                Color::from_hex(0xffcf8eff),
                Color::from_hex(0xff7a7dff),
                Color::from_hex(0xff417dff),
                Color::from_hex(0xd61a88ff),
                Color::from_hex(0x94007aff),
                Color::from_hex(0x42004eff),
                Color::from_hex(0x220029ff),
                Color::from_hex(0x100726ff),
                Color::from_hex(0x25082cff),
                Color::from_hex(0x3d1132ff),
                Color::from_hex(0x73263dff),
                Color::from_hex(0xbd4035ff),
                Color::from_hex(0xed7b39ff),
                Color::from_hex(0xffb84aff),
                Color::from_hex(0xfff540ff),
                Color::from_hex(0xc6d831ff),
                Color::from_hex(0x77b02aff),
                Color::from_hex(0x429058ff),
                Color::from_hex(0x2c645eff),
                Color::from_hex(0x153c4aff),
                Color::from_hex(0x052137ff),
                Color::from_hex(0x0e0421ff),
                Color::from_hex(0x0c0b42ff),
                Color::from_hex(0x032769ff),
                Color::from_hex(0x144491ff),
                Color::from_hex(0x488bd4ff),
                Color::from_hex(0x78d7ffff),
                Color::from_hex(0xb0fff1ff),
                Color::from_hex(0xfaffffff),
                Color::from_hex(0xc7d4e1ff),
                Color::from_hex(0x928fb8ff),
                Color::from_hex(0x5b537dff),
                Color::from_hex(0x392946ff),
                Color::from_hex(0x24142cff),
                Color::from_hex(0x0e0f2cff),
                Color::from_hex(0x132243ff),
                Color::from_hex(0x1a466bff),
                Color::from_hex(0x10908eff),
                Color::from_hex(0x28c074ff),
                Color::from_hex(0x3dff6eff),
                Color::from_hex(0xf8ffb8ff),
                Color::from_hex(0xf0c297ff),
                Color::from_hex(0xcf968cff),
                Color::from_hex(0x8f5765ff),
                Color::from_hex(0x52294bff),
                Color::from_hex(0x0f022eff),
                Color::from_hex(0x35003bff),
                Color::from_hex(0x64004cff),
                Color::from_hex(0x9b0e3eff),
                Color::from_hex(0xd41e3cff),
                Color::from_hex(0xed4c40ff),
                Color::from_hex(0xff9757ff),
                Color::from_hex(0xd4662fff),
                Color::from_hex(0x9c341aff),
                Color::from_hex(0x691b22ff),
                Color::from_hex(0x450c28ff),
                Color::from_hex(0x2d002eff),
            ],
        }
    }
    pub fn endesga64() -> Self {
        Self {
            colors: [
                Color::from_hex(0xff0040ff),
                Color::from_hex(0x131313ff),
                Color::from_hex(0x1b1b1bff),
                Color::from_hex(0x272727ff),
                Color::from_hex(0x3d3d3dff),
                Color::from_hex(0x5d5d5dff),
                Color::from_hex(0x858585ff),
                Color::from_hex(0xb4b4b4ff),
                Color::from_hex(0xffffffff),
                Color::from_hex(0xc7cfddff),
                Color::from_hex(0x92a1b9ff),
                Color::from_hex(0x657392ff),
                Color::from_hex(0x424c6eff),
                Color::from_hex(0x2a2f4eff),
                Color::from_hex(0x1a1932ff),
                Color::from_hex(0x0e071bff),
                Color::from_hex(0x1c121cff),
                Color::from_hex(0x391f21ff),
                Color::from_hex(0x5d2c28ff),
                Color::from_hex(0x8a4836ff),
                Color::from_hex(0xbf6f4aff),
                Color::from_hex(0xe69c69ff),
                Color::from_hex(0xf6ca9fff),
                Color::from_hex(0xf9e6cfff),
                Color::from_hex(0xedab50ff),
                Color::from_hex(0xe07438ff),
                Color::from_hex(0xc64524ff),
                Color::from_hex(0x8e251dff),
                Color::from_hex(0xff5000ff),
                Color::from_hex(0xed7614ff),
                Color::from_hex(0xffa214ff),
                Color::from_hex(0xffc825ff),
                Color::from_hex(0xffeb57ff),
                Color::from_hex(0xd3fc7eff),
                Color::from_hex(0x99e65fff),
                Color::from_hex(0x5ac54fff),
                Color::from_hex(0x33984bff),
                Color::from_hex(0x1e6f50ff),
                Color::from_hex(0x134c4cff),
                Color::from_hex(0x0c2e44ff),
                Color::from_hex(0x00396dff),
                Color::from_hex(0x0069aaff),
                Color::from_hex(0x0098dcff),
                Color::from_hex(0x00cdf9ff),
                Color::from_hex(0x0cf1ffff),
                Color::from_hex(0x94fdffff),
                Color::from_hex(0xfdd2edff),
                Color::from_hex(0xf389f5ff),
                Color::from_hex(0xdb3ffdff),
                Color::from_hex(0x7a09faff),
                Color::from_hex(0x3003d9ff),
                Color::from_hex(0x0c0293ff),
                Color::from_hex(0x03193fff),
                Color::from_hex(0x3b1443ff),
                Color::from_hex(0x622461ff),
                Color::from_hex(0x93388fff),
                Color::from_hex(0xca52c9ff),
                Color::from_hex(0xc85086ff),
                Color::from_hex(0xf68187ff),
                Color::from_hex(0xf5555dff),
                Color::from_hex(0xea323cff),
                Color::from_hex(0xc42430ff),
                Color::from_hex(0x891e2bff),
                Color::from_hex(0x571c27ff),
            ],
        }
    }
    pub fn famicube() -> Self {
        Self {
            colors: [
                Color::from_hex(0x000000ff),
                Color::from_hex(0xe03c28ff),
                Color::from_hex(0xffffffff),
                Color::from_hex(0xd7d7d7ff),
                Color::from_hex(0xa8a8a8ff),
                Color::from_hex(0x7b7b7bff),
                Color::from_hex(0x343434ff),
                Color::from_hex(0x151515ff),
                Color::from_hex(0x0d2030ff),
                Color::from_hex(0x415d66ff),
                Color::from_hex(0x71a6a1ff),
                Color::from_hex(0xbdffcaff),
                Color::from_hex(0x25e2cdff),
                Color::from_hex(0x0a98acff),
                Color::from_hex(0x005280ff),
                Color::from_hex(0x00604bff),
                Color::from_hex(0x20b562ff),
                Color::from_hex(0x58d332ff),
                Color::from_hex(0x139d08ff),
                Color::from_hex(0x004e00ff),
                Color::from_hex(0x172808ff),
                Color::from_hex(0x376d03ff),
                Color::from_hex(0x6ab417ff),
                Color::from_hex(0x8cd612ff),
                Color::from_hex(0xbeeb71ff),
                Color::from_hex(0xeeffa9ff),
                Color::from_hex(0xb6c121ff),
                Color::from_hex(0x939717ff),
                Color::from_hex(0xcc8f15ff),
                Color::from_hex(0xffbb31ff),
                Color::from_hex(0xffe737ff),
                Color::from_hex(0xf68f37ff),
                Color::from_hex(0xad4e1aff),
                Color::from_hex(0x231712ff),
                Color::from_hex(0x5c3c0dff),
                Color::from_hex(0xae6c37ff),
                Color::from_hex(0xc59782ff),
                Color::from_hex(0xe2d7b5ff),
                Color::from_hex(0x4f1507ff),
                Color::from_hex(0x823c3dff),
                Color::from_hex(0xda655eff),
                Color::from_hex(0xe18289ff),
                Color::from_hex(0xf5b784ff),
                Color::from_hex(0xffe9c5ff),
                Color::from_hex(0xff82ceff),
                Color::from_hex(0xcf3c71ff),
                Color::from_hex(0x871646ff),
                Color::from_hex(0xa328b3ff),
                Color::from_hex(0xcc69e4ff),
                Color::from_hex(0xd59cfcff),
                Color::from_hex(0xfec9edff),
                Color::from_hex(0xe2c9ffff),
                Color::from_hex(0xa675feff),
                Color::from_hex(0x6a31caff),
                Color::from_hex(0x5a1991ff),
                Color::from_hex(0x211640ff),
                Color::from_hex(0x3d34a5ff),
                Color::from_hex(0x6264dcff),
                Color::from_hex(0x9ba0efff),
                Color::from_hex(0x98dcffff),
                Color::from_hex(0x5ba8ffff),
                Color::from_hex(0x0a89ffff),
                Color::from_hex(0x024acaff),
                Color::from_hex(0x00177dff),
            ],
        }
    }
    pub fn blknx64() -> Self {
        Self {
            colors: [
                Color::from_hex(0x000000ff),
                Color::from_hex(0x12173dff),
                Color::from_hex(0x293268ff),
                Color::from_hex(0x464b8cff),
                Color::from_hex(0x6b74b2ff),
                Color::from_hex(0x909eddff),
                Color::from_hex(0xc1d9f2ff),
                Color::from_hex(0xffffffff),
                Color::from_hex(0xa293c4ff),
                Color::from_hex(0x7b6aa5ff),
                Color::from_hex(0x53427fff),
                Color::from_hex(0x3c2c68ff),
                Color::from_hex(0x431e66ff),
                Color::from_hex(0x5d2f8cff),
                Color::from_hex(0x854cbfff),
                Color::from_hex(0xb483efff),
                Color::from_hex(0x8cff9bff),
                Color::from_hex(0x42bc7fff),
                Color::from_hex(0x22896eff),
                Color::from_hex(0x14665bff),
                Color::from_hex(0x0f4a4cff),
                Color::from_hex(0x0a2a33ff),
                Color::from_hex(0x1d1a59ff),
                Color::from_hex(0x322d89ff),
                Color::from_hex(0x354ab2ff),
                Color::from_hex(0x3e83d1ff),
                Color::from_hex(0x50b9ebff),
                Color::from_hex(0x8cdaffff),
                Color::from_hex(0x53a1adff),
                Color::from_hex(0x3b768fff),
                Color::from_hex(0x21526bff),
                Color::from_hex(0x163755ff),
                Color::from_hex(0x008782ff),
                Color::from_hex(0x00aaa5ff),
                Color::from_hex(0x27d3cbff),
                Color::from_hex(0x78fae6ff),
                Color::from_hex(0xcdc599ff),
                Color::from_hex(0x988f64ff),
                Color::from_hex(0x5c5d41ff),
                Color::from_hex(0x353f23ff),
                Color::from_hex(0x919b45ff),
                Color::from_hex(0xafd370ff),
                Color::from_hex(0xffe091ff),
                Color::from_hex(0xffaa6eff),
                Color::from_hex(0xff695aff),
                Color::from_hex(0xb23c40ff),
                Color::from_hex(0xff6675ff),
                Color::from_hex(0xdd3745ff),
                Color::from_hex(0xa52639ff),
                Color::from_hex(0x721c2fff),
                Color::from_hex(0xb22e69ff),
                Color::from_hex(0xe54286ff),
                Color::from_hex(0xff6eafff),
                Color::from_hex(0xffa5d5ff),
                Color::from_hex(0xffd3adff),
                Color::from_hex(0xcc817aff),
                Color::from_hex(0x895654ff),
                Color::from_hex(0x61393bff),
                Color::from_hex(0x3f1f3cff),
                Color::from_hex(0x723352ff),
                Color::from_hex(0x994c69ff),
                Color::from_hex(0xc37289ff),
                Color::from_hex(0xf29faaff),
                Color::from_hex(0xffccd0ff),
            ],
        }
    }
    pub fn tpp20() -> Self {
        Self {
            colors: [
                Color::from_hex(0x140e1eff),
                Color::from_hex(0x2d1a71ff),
                Color::from_hex(0x3257beff),
                Color::from_hex(0x409defff),
                Color::from_hex(0x70dbffff),
                Color::from_hex(0xbfffffff),
                Color::from_hex(0x3e32d5ff),
                Color::from_hex(0x6e6affff),
                Color::from_hex(0xa6adffff),
                Color::from_hex(0xd8e0ffff),
                Color::from_hex(0x652bbcff),
                Color::from_hex(0xb44cefff),
                Color::from_hex(0xec8cffff),
                Color::from_hex(0xffcdffff),
                Color::from_hex(0x480e55ff),
                Color::from_hex(0x941887ff),
                Color::from_hex(0xe444c3ff),
                Color::from_hex(0xff91e2ff),
                Color::from_hex(0x190c12ff),
                Color::from_hex(0x550e2bff),
                Color::from_hex(0xaf102eff),
                Color::from_hex(0xff424fff),
                Color::from_hex(0xff9792ff),
                Color::from_hex(0xffd5cfff),
                Color::from_hex(0x491d1eff),
                Color::from_hex(0xaa2c1eff),
                Color::from_hex(0xf66d1eff),
                Color::from_hex(0xffae68ff),
                Color::from_hex(0xffe1b5ff),
                Color::from_hex(0x492917ff),
                Color::from_hex(0x97530fff),
                Color::from_hex(0xdd8c00ff),
                Color::from_hex(0xfbc800ff),
                Color::from_hex(0xfff699ff),
                Color::from_hex(0x0c101bff),
                Color::from_hex(0x0e3e12ff),
                Color::from_hex(0x38741aff),
                Color::from_hex(0x6cb328ff),
                Color::from_hex(0xafe356ff),
                Color::from_hex(0xe4fca2ff),
                Color::from_hex(0x0d384cff),
                Color::from_hex(0x177578ff),
                Color::from_hex(0x00bc9fff),
                Color::from_hex(0x6becbdff),
                Color::from_hex(0xc9fcccff),
                Color::from_hex(0x353234ff),
                Color::from_hex(0x665d5bff),
                Color::from_hex(0x998d86ff),
                Color::from_hex(0xcdbfb3ff),
                Color::from_hex(0xeae6daff),
                Color::from_hex(0x2f3143ff),
                Color::from_hex(0x505d6dff),
                Color::from_hex(0x7b95a0ff),
                Color::from_hex(0xa6cfd0ff),
                Color::from_hex(0xdfeae4ff),
                Color::from_hex(0x8d4131ff),
                Color::from_hex(0xcb734dff),
                Color::from_hex(0xefaf79ff),
                Color::from_hex(0x9c2b3bff),
                Color::from_hex(0xe45761ff),
                Color::from_hex(0xffffffff),
                Color::from_hex(0x000000ff),
                Color::from_hex(0xe4162bff),
                Color::from_hex(0xffff40ff),
            ],
        }
    }
    pub fn sweetcanyonextended64() -> Self {
        Self {
            colors: [
                Color::from_hex(0x0f0e11ff),
                Color::from_hex(0x2d2c33ff),
                Color::from_hex(0x40404aff),
                Color::from_hex(0x51545cff),
                Color::from_hex(0x6b7179ff),
                Color::from_hex(0x7c8389ff),
                Color::from_hex(0xa8b2b6ff),
                Color::from_hex(0xd5d5d5ff),
                Color::from_hex(0xeeebe0ff),
                Color::from_hex(0xf1dbb1ff),
                Color::from_hex(0xeec99fff),
                Color::from_hex(0xe1a17eff),
                Color::from_hex(0xcc9562ff),
                Color::from_hex(0xab7b49ff),
                Color::from_hex(0x9a643aff),
                Color::from_hex(0x86482fff),
                Color::from_hex(0x783a29ff),
                Color::from_hex(0x6a3328ff),
                Color::from_hex(0x541d29ff),
                Color::from_hex(0x42192cff),
                Color::from_hex(0x512240ff),
                Color::from_hex(0x782349ff),
                Color::from_hex(0x8b2e5dff),
                Color::from_hex(0xa93e89ff),
                Color::from_hex(0xd062c8ff),
                Color::from_hex(0xec94eaff),
                Color::from_hex(0xf2bdfcff),
                Color::from_hex(0xeaebffff),
                Color::from_hex(0xa2fafaff),
                Color::from_hex(0x64e7e7ff),
                Color::from_hex(0x54cfd8ff),
                Color::from_hex(0x2fb6c3ff),
                Color::from_hex(0x2c89afff),
                Color::from_hex(0x25739dff),
                Color::from_hex(0x2a5684ff),
                Color::from_hex(0x214574ff),
                Color::from_hex(0x1f2966ff),
                Color::from_hex(0x101445ff),
                Color::from_hex(0x3c0d3bff),
                Color::from_hex(0x66164cff),
                Color::from_hex(0x901f3dff),
                Color::from_hex(0xbb3030ff),
                Color::from_hex(0xdc473cff),
                Color::from_hex(0xec6a45ff),
                Color::from_hex(0xfb9b41ff),
                Color::from_hex(0xf0c04cff),
                Color::from_hex(0xf4d66eff),
                Color::from_hex(0xfffb76ff),
                Color::from_hex(0xccf17aff),
                Color::from_hex(0x97d948ff),
                Color::from_hex(0x6fba3bff),
                Color::from_hex(0x229443ff),
                Color::from_hex(0x1d7e45ff),
                Color::from_hex(0x116548ff),
                Color::from_hex(0x0c4f3fff),
                Color::from_hex(0x0a3639ff),
                Color::from_hex(0x251746ff),
                Color::from_hex(0x48246dff),
                Color::from_hex(0x69189cff),
                Color::from_hex(0x9f20c0ff),
                Color::from_hex(0xe527d2ff),
                Color::from_hex(0xff51cfff),
                Color::from_hex(0xff7adaff),
                Color::from_hex(0xff9edbff),
            ],
        }
    }
    pub fn pastel64() -> Self {
        Self {
            colors: [
                Color::from_hex(0x998276ff),
                Color::from_hex(0xc4c484ff),
                Color::from_hex(0xabd883ff),
                Color::from_hex(0xa2f2bdff),
                Color::from_hex(0xb88488ff),
                Color::from_hex(0xd1b182ff),
                Color::from_hex(0xd4eb91ff),
                Color::from_hex(0xccfcc4ff),
                Color::from_hex(0x907699ff),
                Color::from_hex(0xc484a4ff),
                Color::from_hex(0xea8c79ff),
                Color::from_hex(0xf2e5a2ff),
                Color::from_hex(0x9a84b8ff),
                Color::from_hex(0xd182caff),
                Color::from_hex(0xeb91a8ff),
                Color::from_hex(0xffddc4ff),
                Color::from_hex(0x768d99ff),
                Color::from_hex(0x8484c4ff),
                Color::from_hex(0xc479eaff),
                Color::from_hex(0xf2a2d7ff),
                Color::from_hex(0x84b8b4ff),
                Color::from_hex(0x82a2d1ff),
                Color::from_hex(0xa791ebff),
                Color::from_hex(0xfbc8f5ff),
                Color::from_hex(0x7c957aff),
                Color::from_hex(0x84c4a4ff),
                Color::from_hex(0x79d7eaff),
                Color::from_hex(0xa2aff2ff),
                Color::from_hex(0xa2b884ff),
                Color::from_hex(0x82d189ff),
                Color::from_hex(0x91ebd4ff),
                Color::from_hex(0xc9e5faff),
                Color::from_hex(0xb8a784ff),
                Color::from_hex(0xb9ca89ff),
                Color::from_hex(0x91eb91ff),
                Color::from_hex(0xc9fce9ff),
                Color::from_hex(0x957686ff),
                Color::from_hex(0xc49484ff),
                Color::from_hex(0xeade7aff),
                Color::from_hex(0xc3f2a2ff),
                Color::from_hex(0xb884afff),
                Color::from_hex(0xd1828fff),
                Color::from_hex(0xebbd91ff),
                Color::from_hex(0xf7f9c4ff),
                Color::from_hex(0x797699ff),
                Color::from_hex(0xb484c4ff),
                Color::from_hex(0xea79bbff),
                Color::from_hex(0xf2a9a2ff),
                Color::from_hex(0x8495b8ff),
                Color::from_hex(0x9d82d1ff),
                Color::from_hex(0xea91ebff),
                Color::from_hex(0xffc8d4ff),
                Color::from_hex(0x76958dff),
                Color::from_hex(0x84b4c4ff),
                Color::from_hex(0x7982eaff),
                Color::from_hex(0xd1a2f2ff),
                Color::from_hex(0x84b88dff),
                Color::from_hex(0x82d1c4ff),
                Color::from_hex(0x91beebff),
                Color::from_hex(0xd2c6faff),
                Color::from_hex(0x969976ff),
                Color::from_hex(0x94c484ff),
                Color::from_hex(0x79eaa8ff),
                Color::from_hex(0xa2ebf2ff),
            ],
        }
    }
    pub fn rewild64() -> Self {
        Self {
            colors: [
                Color::from_hex(0x172038ff),
                Color::from_hex(0x253a5eff),
                Color::from_hex(0x3c5e8bff),
                Color::from_hex(0x4f8fbaff),
                Color::from_hex(0x73bed3ff),
                Color::from_hex(0xa4dddbff),
                Color::from_hex(0x193024ff),
                Color::from_hex(0x245938ff),
                Color::from_hex(0x2b8435ff),
                Color::from_hex(0x62ac4cff),
                Color::from_hex(0xa2dc6eff),
                Color::from_hex(0xc5e49bff),
                Color::from_hex(0x19332dff),
                Color::from_hex(0x25562eff),
                Color::from_hex(0x468232ff),
                Color::from_hex(0x75a743ff),
                Color::from_hex(0xa8ca58ff),
                Color::from_hex(0xd0da91ff),
                Color::from_hex(0x5f6d43ff),
                Color::from_hex(0x97933aff),
                Color::from_hex(0xa9b74cff),
                Color::from_hex(0xcfd467ff),
                Color::from_hex(0xd5dc97ff),
                Color::from_hex(0xd6dea6ff),
                Color::from_hex(0x382a28ff),
                Color::from_hex(0x43322fff),
                Color::from_hex(0x564238ff),
                Color::from_hex(0x715a42ff),
                Color::from_hex(0x867150ff),
                Color::from_hex(0xb1a282ff),
                Color::from_hex(0x4d2b32ff),
                Color::from_hex(0x7a4841ff),
                Color::from_hex(0xad7757ff),
                Color::from_hex(0xc09473ff),
                Color::from_hex(0xd7b594ff),
                Color::from_hex(0xe7d5b3ff),
                Color::from_hex(0x341c27ff),
                Color::from_hex(0x602c2cff),
                Color::from_hex(0x884b2bff),
                Color::from_hex(0xbe772bff),
                Color::from_hex(0xde9e41ff),
                Color::from_hex(0xe8c170ff),
                Color::from_hex(0x241527ff),
                Color::from_hex(0x411d31ff),
                Color::from_hex(0x752438ff),
                Color::from_hex(0xa53030ff),
                Color::from_hex(0xcf573cff),
                Color::from_hex(0xda863eff),
                Color::from_hex(0x1e1d39ff),
                Color::from_hex(0x402751ff),
                Color::from_hex(0x7a367bff),
                Color::from_hex(0xa23e8cff),
                Color::from_hex(0xc65197ff),
                Color::from_hex(0xdf84a5ff),
                Color::from_hex(0x090a14ff),
                Color::from_hex(0x10141fff),
                Color::from_hex(0x151d28ff),
                Color::from_hex(0x202e37ff),
                Color::from_hex(0x394a50ff),
                Color::from_hex(0x577277ff),
                Color::from_hex(0x819796ff),
                Color::from_hex(0xa8b5b2ff),
                Color::from_hex(0xc7cfccff),
                Color::from_hex(0xebede9ff),
            ],
        }
    }
}

impl Default for Palette {
    fn default() -> Self {
        Self {
            colors: [Color::default(); PALETTE_COLORS],
        }
    }
}
