// This file is @generated by prost-build.
pub mod auth {
    include!("auth.rs");
}
pub mod author {
    include!("author.rs");
}
pub mod chat {
    include!("chat.rs");
}
pub mod common {
    include!("common.rs");
}
pub mod game {
    include!("game.rs");
}
pub mod platform {
    include!("platform.rs");
}
pub mod review {
    include!("review.rs");
}
pub mod tag {
    include!("tag.rs");
}
pub mod users {
    include!("users.rs");
}
